version: "3.4"

services:
  app:
    build:
      dockerfile: ./ops/docker/app/Dockerfile
      context: ./
      target: dev
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/html
  db:
    image: timescale/timescaledb:latest-pg11
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=change_this
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_data:
